import { Match, Option, Schema } from "effect";
import {
	type DraftPrRecommendation,
	draftPrRecommendationSchema,
	type PatchProposal,
	patchProposalSchema,
} from "./AiAdvisory";

export const githubDraftPrSyncAdvisorySchema = Schema.Struct({
	draftPr: Schema.optional(draftPrRecommendationSchema),
	patchProposal: Schema.optional(patchProposalSchema),
});

export const githubDraftPrSyncAdvisoryJsonSchema = Schema.fromJsonString(
	githubDraftPrSyncAdvisorySchema,
);

export const githubOpenPullRequestSchema = Schema.Struct({
	number: Schema.Number.check(Schema.isInt(), Schema.isGreaterThan(0)),
	title: Schema.String,
	body: Schema.optional(Schema.String),
	headRef: Schema.String,
});

export const githubCreateDraftPrSchema = Schema.Struct({
	_tag: Schema.Literal("CreateGithubDraftPr"),
	branchName: Schema.String,
	title: Schema.String,
	body: Schema.String,
	comment: Schema.String,
	proposalPath: Schema.String,
	proposalContent: Schema.String,
});

export const githubUpdateDraftPrSchema = Schema.Struct({
	_tag: Schema.Literal("UpdateGithubDraftPr"),
	number: Schema.Number.check(Schema.isInt(), Schema.isGreaterThan(0)),
	branchName: Schema.String,
	title: Schema.String,
	body: Schema.String,
	proposalPath: Schema.String,
	proposalContent: Schema.String,
});

export type GithubDraftPrSyncAdvisory = typeof githubDraftPrSyncAdvisorySchema.Type;
export type GithubOpenPullRequest = typeof githubOpenPullRequestSchema.Type;
export type GithubDraftPrAction =
	| typeof githubCreateDraftPrSchema.Type
	| typeof githubUpdateDraftPrSchema.Type;

const draftPrMarker = (branchName: string) => `<!-- doc-freshness-draft-pr:${branchName} -->`;

const safeFileSegment = (value: string) =>
	value
		.toLowerCase()
		.replaceAll(/[^a-z0-9]+/g, "-")
		.replaceAll(/^-|-$/g, "")
		.slice(0, 96);

const proposalFilePath = (draftPr: DraftPrRecommendation) =>
	`.github/doc-freshness/draft-prs/${safeFileSegment(draftPr.branchName) || "patch-proposal"}.md`;

const markdownList = (items: ReadonlyArray<string>, fallback: string) =>
	Match.value(items.length > 0).pipe(
		Match.when(true, () => items.map((item) => `- ${item}`).join("\n")),
		Match.orElse(() => `- ${fallback}`),
	);

const humanReviewLabel = (requiresHumanReview: boolean) =>
	Match.value(requiresHumanReview).pipe(
		Match.when(true, () => "yes"),
		Match.orElse(() => "no"),
	);

const renderedPatchProposalSection = (availableProposal: PatchProposal) =>
	[
		`Status: \`${availableProposal.status}\``,
		"",
		`Target document: \`${availableProposal.path}\``,
		"",
		`Human review required: \`${humanReviewLabel(availableProposal.requiresHumanReview)}\``,
		"",
		"### Rationale",
		"",
		availableProposal.rationale,
		"",
		"### Proposed changes",
		"",
		markdownList(
			availableProposal.proposedChanges,
			"Review the generated advisory report manually.",
		),
		"",
		"### Patch proposal artifact",
		"",
		availableProposal.markdownArtifact,
	].join("\n");

const patchProposalSection = (proposal: PatchProposal | undefined) =>
	Option.match(Option.fromNullishOr(proposal), {
		onNone: () => "No structured patch proposal was attached to the advisory payload.",
		onSome: renderedPatchProposalSection,
	});

const proposalContent = (draftPr: DraftPrRecommendation, proposal: PatchProposal | undefined) =>
	[
		draftPrMarker(draftPr.branchName),
		"",
		"# Docs Librarian draft PR proposal",
		"",
		"This file is generated by the doc-freshness workflow so the Docs Librarian can open a draft pull request for one focused human review item.",
		"",
		`Recommended branch: \`${draftPr.branchName}\``,
		"",
		`Recommended PR title: ${draftPr.title}`,
		"",
		"## Why this PR exists",
		"",
		draftPr.reason,
		"",
		"## Suggested PR body",
		"",
		draftPr.body,
		"",
		"## Suggested Docs Librarian comment",
		"",
		draftPr.comment,
		"",
		"## Structured patch proposal",
		"",
		patchProposalSection(proposal),
		"",
		"## Maintainer checklist",
		"",
		"- [ ] Review the proposed documentation change.",
		"- [ ] Apply the safe parts to the target document.",
		"- [ ] Remove or update this generated proposal file before merge if it is no longer useful.",
	].join("\n");

const existingPullForBranch = (
	branchName: string,
	pullRequests: ReadonlyArray<GithubOpenPullRequest>,
) => Option.fromNullishOr(pullRequests.find((pullRequest) => pullRequest.headRef === branchName));

const readyDraftPr = (advisory: GithubDraftPrSyncAdvisory) =>
	Option.filter(
		Option.fromNullishOr(advisory.draftPr),
		(draftPr) => draftPr.status === "ready" && draftPr.branchName !== "n/a",
	);

const createAction = (
	draftPr: DraftPrRecommendation,
	proposal: PatchProposal | undefined,
): GithubDraftPrAction =>
	githubCreateDraftPrSchema.make({
		_tag: "CreateGithubDraftPr",
		branchName: draftPr.branchName,
		title: draftPr.title,
		body: draftPr.body,
		comment: draftPr.comment,
		proposalPath: proposalFilePath(draftPr),
		proposalContent: proposalContent(draftPr, proposal),
	});

const updateAction = (
	draftPr: DraftPrRecommendation,
	proposal: PatchProposal | undefined,
	pullRequest: GithubOpenPullRequest,
): GithubDraftPrAction =>
	githubUpdateDraftPrSchema.make({
		_tag: "UpdateGithubDraftPr",
		number: pullRequest.number,
		branchName: draftPr.branchName,
		title: draftPr.title,
		body: draftPr.body,
		proposalPath: proposalFilePath(draftPr),
		proposalContent: proposalContent(draftPr, proposal),
	});

const actionForDraftPr = (
	draftPr: DraftPrRecommendation,
	proposal: PatchProposal | undefined,
	pullRequests: ReadonlyArray<GithubOpenPullRequest>,
) =>
	Option.match(existingPullForBranch(draftPr.branchName, pullRequests), {
		onNone: () => createAction(draftPr, proposal),
		onSome: (pullRequest) => updateAction(draftPr, proposal, pullRequest),
	});

export const planGithubDraftPr = (
	advisory: GithubDraftPrSyncAdvisory,
	pullRequests: ReadonlyArray<GithubOpenPullRequest>,
): ReadonlyArray<GithubDraftPrAction> =>
	Option.match(readyDraftPr(advisory), {
		onNone: () => [],
		onSome: (draftPr) => [actionForDraftPr(draftPr, advisory.patchProposal, pullRequests)],
	});
